name: CI-CD

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda install -y python=3.10
          conda env update --file environment.yml --name base 

      - name: Install package and its entry points
        run: |
          pip install .

      - name: Install linter and formatter
        run: |
          python -m pip install shyaml flake8 black black-nb flake8-nb

      - name: Run black formatter
        run: |
          black -l 99 .

      - name: Install pytest and run tests
        run: |
          pip install pytest pytest-cov
          pytest -vv --cov=openmmdl --cov-report=xml --cov-report=html --color=yes openmmdl/tests/
